set_property PACKAGE_PIN U22 [get_ports sys_clk]
set_property PACKAGE_PIN P4 [get_ports rstn]
set_property PACKAGE_PIN D26 [get_ports {IO_data[0]}]
set_property PACKAGE_PIN D25 [get_ports {IO_data[2]}]
set_property PACKAGE_PIN G26 [get_ports {IO_data[4]}]
set_property PACKAGE_PIN E23 [get_ports {IO_data[6]}]
set_property PACKAGE_PIN F22 [get_ports {IO_data[8]}]
set_property PACKAGE_PIN J26 [get_ports {IO_data[10]}]
set_property PACKAGE_PIN G21 [get_ports {IO_data[12]}]

set_property PACKAGE_PIN E25 [get_ports {IO_data[1]}]
set_property PACKAGE_PIN H26 [get_ports {IO_data[3]}]
set_property PACKAGE_PIN F23 [get_ports {IO_data[5]}]
set_property PACKAGE_PIN G22 [get_ports {IO_data[7]}]
set_property PACKAGE_PIN J25 [get_ports {IO_data[9]}]
set_property PACKAGE_PIN G20 [get_ports {IO_data[11]}]


set_property IOSTANDARD LVCMOS33 [get_ports sys_clk]
set_property IOSTANDARD LVCMOS33 [get_ports rstn]
set_property IOSTANDARD LVCMOS33 [get_ports {IO_data[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IO_data[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IO_data[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IO_data[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IO_data[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IO_data[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IO_data[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IO_data[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IO_data[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IO_data[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IO_data[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IO_data[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IO_data[0]}]

set_property BITSTREAM.CONFIG.SPI_BUSWIDTH 4 [current_design]

set_property PACKAGE_PIN U2 [get_ports uart_txd]
set_property IOSTANDARD LVCMOS33 [get_ports uart_txd]

set_property PACKAGE_PIN U1 [get_ports uart_rxd]
set_property IOSTANDARD LVCMOS33 [get_ports uart_rxd]
set_property IOSTANDARD LVCMOS33 [get_ports {PULSE_data[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PULSE_data[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PULSE_data[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PULSE_data[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PULSE_data[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PULSE_data[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PULSE_data[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PULSE_data[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PULSE_data[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PULSE_data[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PULSE_data[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PULSE_data[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PULSE_data[12]}]

set_property PACKAGE_PIN E26 [get_ports clk_AD1]
set_property IOSTANDARD LVCMOS33 [get_ports clk_AD1]
set_property IOSTANDARD LVCMOS33 [get_ports clk_AD2]
set_property PACKAGE_PIN B4 [get_ports {PULSE_data[12]}]
set_property PACKAGE_PIN A3 [get_ports {PULSE_data[10]}]
set_property PACKAGE_PIN D4 [get_ports {PULSE_data[8]}]
set_property PACKAGE_PIN C2 [get_ports {PULSE_data[6]}]
set_property PACKAGE_PIN E5 [get_ports {PULSE_data[4]}]
set_property PACKAGE_PIN C1 [get_ports {PULSE_data[2]}]
set_property PACKAGE_PIN E1 [get_ports {PULSE_data[0]}]
set_property PACKAGE_PIN A4 [get_ports {PULSE_data[11]}]
set_property PACKAGE_PIN A2 [get_ports {PULSE_data[9]}]
set_property PACKAGE_PIN C4 [get_ports {PULSE_data[7]}]
set_property PACKAGE_PIN B2 [get_ports {PULSE_data[5]}]
set_property PACKAGE_PIN D5 [get_ports {PULSE_data[3]}]
set_property PACKAGE_PIN B1 [get_ports {PULSE_data[1]}]

set_property PACKAGE_PIN D1 [get_ports clk_AD2]
